### ISSUE TITLE
nonexistent packages

### ISSUE THREAD

**Issue by debugteam** [eSlider/vis-ui.js#5]
May i suggest to replace nonexistent packages:

"components/jquerydialogextendjs": "*"
"components/placeholdersjs": "*"

with:

"wg-rolf/placeholdersjs": "v1.0.0"
"wg-rolf/jquery-dialogextend": "v1.0.0"

**Comment by eSlider** [comment]
https://github.com/eSlider/vis-ui.js/commit/ca4426588a854b896796c55e82c6168066f97500
https://github.com/eSlider/vis-ui.js/commit/d29c319a95c6385fe90f614db2f48ee1a6cd5be3
