### ISSUE TITLE
vis-ui.js breaks jquery-UI dialog

### ISSUE THREAD

**Issue by DavidPatzke** [eSlider/vis-ui.js#9]
Initializing a jQuery UI dialog will end in an endless loop. 

```
 // fake dialogExtend check for ui-dialog
    $.fn["dialog"] = function(arg1, arg2) {
        return this.hasClass('popup-dialog') ? this.popupDialog(arg1, arg2) : this.dialog(arg1, arg2);
    };
```
Calling dialog() will check for class 'popup-dialog' and if this class is not available it will check again and again.
We need to save the original dialog function somewhere before overwriting it to correctly monkey patch here.

```
 // fake dialogExtend check for ui-dialog
    $.fn..orignalDialogFunc = $.fn["dialog"];
    $.fn["dialog"] = function(arg1, arg2) {
        return this.hasClass('popup-dialog') ? this.popupDialog(arg1, arg2) :  this.orignalDialogFunc(arg1, arg2);
    };


```

**Comment by eSlider** [comment]
@LazerTiberius wann kommt das vor? Beispiele!

**Comment by DavidPatzke** [comment]
Wie ich bereits geschrieben habe: Einfach ```$('<div>').dialog();``` aufrufen, um einen standard jQuerUi Dialog zu erzeugen. Ich habe meinen Patch jetzt aber schon gemerged!

**Comment by eSlider** [comment]
Rictiger Aufruf lautet:  
```js
$("<div/>").popupDialog()
```

**Comment by DavidPatzke** [comment]
http://api.jqueryui.com/dialog/
